spring:
  application:
    name: ai-service

server:
  port: 2050

ollama:
  url: http://localhost:11434/api/generate
  embeddings-url: http://localhost:11434/api/embeddings
  model: llama3.2:3b  
  emd-model:  nomic-embed-text
